// src/views/Contact.jsx
"use client";

import { useEffect, useRef, useState } from "react";
import emailjs from "@emailjs/browser";
import Reveal from "../components/Reveal";

const SERVICE_ID = process.env.NEXT_PUBLIC_EMAILJS_SERVICE_ID || "service_1ajllgm";
const TEMPLATE_ID = process.env.NEXT_PUBLIC_EMAILJS_TEMPLATE_ID || "template_mtqwxq5";
const PUBLIC_KEY = process.env.NEXT_PUBLIC_EMAILJS_PUBLIC_KEY || "zV-JGz4jw4hDv3m2h";
const initialForm = { name: "", email: "", message: "" };

export default function Contact() {
  const [form, setForm] = useState(initialForm);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [submitText, setSubmitText] = useState("Send Message");
  const [messageText, setMessageText] = useState("");
  const statusTimer = useRef(null);

  useEffect(() => () => {
    if (statusTimer.current) window.clearTimeout(statusTimer.current);
  }, []);

  const updateField = (event) => {
    setForm((current) => ({ ...current, [event.target.name]: event.target.value }));
  };

  const submitForm = async (event) => {
    event.preventDefault();
    setIsSubmitting(true);
    setSubmitText("Sending...");
    setMessageText("");

    try {
      await emailjs.send(SERVICE_ID, TEMPLATE_ID, form, PUBLIC_KEY);
      setSubmitText("Message Sent");
      setMessageText("Your message has been sent.");
      setForm(initialForm);
    } catch (error) {
      console.error("EmailJS Error:", error);
      setSubmitText("Send Failed");
      setMessageText("Failed to send. Please try again.");
    } finally {
      statusTimer.current = window.setTimeout(() => {
        setSubmitText("Send Message");
        setIsSubmitting(false);
        setMessageText("");
      }, 3500);
    }
  };

  return (
    <section className="relative overflow-hidden bg-ink/88 py-[5.5rem]">
      <div className="pointer-events-none absolute -top-1/2 left-1/2 size-[31.25rem] -translate-x-1/2 rounded-full bg-[radial-gradient(circle,rgba(212,175,55,0.08),transparent_70%)]" aria-hidden="true" />
      <div className="mx-auto w-full max-w-[90rem] px-5 sm:px-8 md:px-12 lg:px-20 2xl:max-w-none 2xl:px-[clamp(6rem,7vw,13.75rem)]">
        <Reveal className="relative z-10 mx-auto max-w-[47.5rem] text-center">
          <p className="m-0 text-xs font-bold uppercase tracking-[0.12em] text-amber">Contact</p>
          <h2 className="mt-3 bg-gradient-to-br from-copy to-amber-light bg-clip-text text-[clamp(2.2rem,5vw,4rem)] font-semibold leading-tight tracking-[-0.055em] text-transparent">Let’s work together.</h2>
          <p className="mt-4 text-base leading-7 text-muted">Software, product UI, and websites.</p>

          <div className="mt-8 flex flex-wrap justify-center gap-3">
            <a href="mailto:yjevin75@gmail.com" className="rounded-full border border-amber bg-amber px-4 py-2.5 text-sm font-semibold text-ink transition hover:-translate-y-0.5 hover:bg-amber-light focus-visible:outline-2 focus-visible:outline-offset-3 focus-visible:outline-cyan">yjevin75@gmail.com</a>
          </div>

          {messageText ? <div className="mt-6 text-muted" role="status">{messageText}</div> : null}

          <form className="mt-8 flex flex-col gap-3" onSubmit={submitForm}>
            <input name="name" value={form.name} onChange={updateField} type="text" placeholder="Name" required className="w-full rounded-2xl border border-amber/20 bg-gradient-to-br from-panel to-panel/50 px-4 py-4 text-copy outline-none transition placeholder:text-muted focus:border-amber focus:shadow-[0_0_24px_rgba(212,175,55,0.15)]" />
            <input name="email" value={form.email} onChange={updateField} type="email" placeholder="Email" required className="w-full rounded-2xl border border-amber/20 bg-gradient-to-br from-panel to-panel/50 px-4 py-4 text-copy outline-none transition placeholder:text-muted focus:border-amber focus:shadow-[0_0_24px_rgba(212,175,55,0.15)]" />
            <textarea name="message" value={form.message} onChange={updateField} placeholder="Tell me about your project" rows={5} required className="w-full resize-y rounded-2xl border border-amber/20 bg-gradient-to-br from-panel to-panel/50 px-4 py-4 text-copy outline-none transition placeholder:text-muted focus:border-amber focus:shadow-[0_0_24px_rgba(212,175,55,0.15)]" />
            <button type="submit" className="mx-auto min-w-44 rounded-full bg-gradient-to-br from-amber to-amber-light px-5 py-4 text-sm font-bold text-ink transition hover:-translate-y-0.5 hover:shadow-2xl hover:shadow-amber/20 focus-visible:outline-2 focus-visible:outline-offset-3 focus-visible:outline-cyan disabled:cursor-not-allowed disabled:opacity-60" disabled={isSubmitting}>{submitText}</button>
          </form>
        </Reveal>
      </div>
    </section>
  );
}

// src/views/Contact.vue
<template>
  <section class="contact">
    <div class="site-container">
      <div class="contact-shell">
        <p class="contact-eyebrow">Contact</p>
        <h2 class="contact-title">Let’s work together.</h2>
        <p class="contact-text">
          For software engineering, product UI, and website projects.
        </p>

        <div class="contact-links">
          <a
            href="mailto:yjevin75@gmail.com"
            class="contact-link contact-link-primary interactive"
          >
            yjevin75@gmail.com
          </a>
        </div>

        <div v-if="messageText" class="message-display">
          {{ messageText }}
        </div>

        <form class="contact-form" @submit.prevent="submitForm">
          <input
            v-model="form.name"
            type="text"
            placeholder="Name"
            required
            class="form-input"
          />
          <input
            v-model="form.email"
            type="email"
            placeholder="Email"
            required
            class="form-input"
          />
          <textarea
            v-model="form.message"
            placeholder="Tell me about your project"
            rows="5"
            required
            class="form-input"
          ></textarea>
          <button
            type="submit"
            class="submit-btn interactive"
            :disabled="isSubmitting"
          >
            {{ submitText }}
          </button>
        </form>
      </div>
    </div>
  </section>
</template>

<script setup>
import { ref, reactive, onBeforeUnmount } from "vue";
import emailjs from "@emailjs/browser";

const SERVICE_ID = "service_1ajllgm";
const TEMPLATE_ID = "template_mtqwxq5";
const PUBLIC_KEY = "zV-JGz4jw4hDv3m2h";

const isSubmitting = ref(false);
const submitText = ref("Send Message");
const messageText = ref(null);
let statusTimer = null;

const form = reactive({
  name: "",
  email: "",
  message: "",
});

emailjs.init({
  publicKey: PUBLIC_KEY,
});

const resetForm = () => {
  form.name = "";
  form.email = "";
  form.message = "";
};

const clearStatusTimer = () => {
  if (statusTimer) {
    clearTimeout(statusTimer);
    statusTimer = null;
  }
};

const resetUiState = () => {
  submitText.value = "Send Message";
  isSubmitting.value = false;
  messageText.value = null;
};

const submitForm = async () => {
  clearStatusTimer();
  isSubmitting.value = true;
  submitText.value = "Sending...";
  messageText.value = null;

  try {
    await emailjs.send(
      SERVICE_ID,
      TEMPLATE_ID,
      {
        name: form.name,
        email: form.email,
        message: form.message,
      },
      PUBLIC_KEY // ✅ only this needed
    );

    submitText.value = "Message Sent";
    messageText.value = "Your message has been sent.";
    resetForm();

    statusTimer = setTimeout(resetUiState, 3000);
  } catch (error) {
    console.error("EmailJS Error:", error);

    submitText.value = "Send Failed";
    messageText.value = "Failed to send. Check setup.";
    statusTimer = setTimeout(resetUiState, 4000);
  }
};

onBeforeUnmount(() => {
  clearStatusTimer();
});
</script>

<style scoped>
.contact {
  padding: 5.5rem 0;
  background: var(--bg-primary);
  position: relative;
  overflow: hidden;
}

.contact::before {
  content: "";
  position: absolute;
  top: -50%;
  left: 50%;
  width: 500px;
  height: 500px;
  background: radial-gradient(
    circle,
    rgba(212, 175, 55, 0.08) 0%,
    transparent 70%
  );
  pointer-events: none;
  transform: translateX(-50%);
}

.contact-shell {
  max-width: 760px;
  margin: 0 auto;
  text-align: center;
  position: relative;
  z-index: 1;
  animation: slideInUp 0.8s ease-out 0.1s both;
}

@keyframes slideInUp {
  from {
    opacity: 0;
    transform: translateY(40px);
  }
  to {
    opacity: 1;
    transform: translateY(0);
  }
}

.contact-eyebrow {
  font-size: 0.82rem;
  font-weight: 600;
  letter-spacing: 0.08em;
  text-transform: uppercase;
  color: var(--gold);
  opacity: 0.8;
}

.contact-title {
  margin-top: 0.9rem;
  font-size: clamp(2.2rem, 5vw, 4rem);
  line-height: 1.02;
  letter-spacing: -0.04em;
  background: linear-gradient(
    135deg,
    var(--text-primary) 0%,
    var(--gold-light) 100%
  );
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
  background-clip: text;
}

.contact-text {
  margin-top: 1rem;
  font-size: 1rem;
  line-height: 1.7;
  color: var(--text-secondary);
}

.contact-links {
  display: flex;
  justify-content: center;
  gap: 0.8rem;
  flex-wrap: wrap;
  margin-top: 2rem;
}

.contact-link {
  padding: 0.68rem 1rem;
  border-radius: 999px;
  background: linear-gradient(
    135deg,
    var(--bg-surface) 0%,
    rgba(26, 26, 26, 0.5) 100%
  );
  border: 1.5px solid var(--gold-border);
  color: var(--gold);
  text-decoration: none;
  font-size: 0.9rem;
  line-height: 1;
  font-weight: 500;
  transition: all 0.3s cubic-bezier(0.34, 1.56, 0.64, 1);
}

.contact-link-primary {
  background: var(--gold);
  color: var(--bg-primary);
  border-color: var(--gold);
}

.contact-form {
  display: flex;
  flex-direction: column;
  gap: 0.9rem;
  margin-top: 2rem;
}

.form-input {
  width: 100%;
  padding: 1rem 1.1rem;
  border: 1.5px solid var(--gold-border);
  border-radius: 20px;
  background: linear-gradient(
    135deg,
    var(--bg-surface) 0%,
    rgba(26, 26, 26, 0.5) 100%
  );
  color: var(--text-primary);
  font-size: 0.98rem;
  font-family: inherit;
  transition: all 0.3s ease;
}

.form-input::placeholder {
  color: var(--text-secondary);
}

.form-input:focus {
  outline: none;
  border-color: var(--gold);
  background: linear-gradient(
    135deg,
    rgba(26, 26, 26, 0.8) 0%,
    rgba(26, 26, 26, 0.4) 100%
  );
  box-shadow: 0 0 24px rgba(212, 175, 55, 0.2);
}

.submit-btn {
  align-self: center;
  min-width: 180px;
  padding: 0.95rem 1.25rem;
  border: none;
  border-radius: 999px;
  background: linear-gradient(135deg, var(--gold) 0%, var(--gold-light) 100%);
  color: var(--bg-primary);
  font-size: 0.95rem;
  font-family: inherit;
  font-weight: 600;
  transition: all 0.3s cubic-bezier(0.34, 1.56, 0.64, 1);
  cursor: pointer;
}

.submit-btn:hover:not(:disabled) {
  transform: translateY(-2px);
  box-shadow: 0 12px 32px rgba(212, 175, 55, 0.3);
}

.submit-btn:active:not(:disabled) {
  transform: translateY(0);
}

.submit-btn:disabled {
  opacity: 0.6;
  cursor: not-allowed;
}

.message-display {
  margin-top: 1.5rem;
  color: var(--text-secondary);
  animation: slideInUp 0.6s ease-out;
}

@media (hover: hover) and (pointer: fine) {
  .contact-link:hover {
    transform: translateY(-4px);
    border-color: var(--gold);
    background: linear-gradient(
      135deg,
      rgba(26, 26, 26, 0.9) 0%,
      rgba(26, 26, 26, 0.6) 100%
    );
  }

  .contact-link-primary:hover {
    background: linear-gradient(135deg, var(--gold-light) 0%, var(--gold) 100%);
  }
}
</style>
