// src/views/Hero.vue
<template>
  <section
    ref="hero"
    class="hero"
    @pointermove="handlePointerMove"
    @pointerleave="resetPointer"
  >
    <div class="hero-grid" aria-hidden="true"></div>
    <div class="hero-grain" aria-hidden="true"></div>
    <div class="hero-halo halo-left" aria-hidden="true"></div>
    <div class="hero-halo halo-right" aria-hidden="true"></div>

    <div class="hero-shell site-container">
      <div class="hero-copy">
        <p class="hero-eyebrow"><span></span>Independent software engineer</p>
        <h1>
          Products that stay
          <em>sharp under pressure.</em>
        </h1>
        <p class="hero-intro">
          I turn complex product ideas into thoughtful web experiences and
          dependable software systems.
        </p>

        <div class="hero-actions">
          <a class="hero-button hero-button-primary interactive" href="#works">
            View selected work <span aria-hidden="true">↗</span>
          </a>
          <a class="hero-button hero-button-secondary interactive" href="#contact">
            Start a project
          </a>
        </div>

        <div class="hero-meta" aria-label="Professional focus">
          <div>
            <strong>01</strong>
            <span>Web platforms</span>
          </div>
          <div>
            <strong>02</strong>
            <span>Product systems</span>
          </div>
          <div>
            <strong>03</strong>
            <span>Focused delivery</span>
          </div>
        </div>
      </div>

      <div class="hero-visual" aria-hidden="true">
        <div class="visual-aura"></div>
        <div class="visual-system">
          <svg
            class="fracture-map"
            viewBox="0 0 600 620"
            fill="none"
            preserveAspectRatio="none"
          >
            <path d="M31 48L230 205L184 389L468 574" />
            <path d="M230 205L526 62" />
            <path d="M230 205L449 302L578 456" />
            <path d="M184 389L18 495" />
            <path d="M184 389L349 498L543 608" />
            <path d="M449 302L493 175" />
            <path d="M349 498L394 616" />
            <circle cx="230" cy="205" r="5" />
            <circle cx="184" cy="389" r="4" />
          </svg>

          <div class="glass-plane glass-plane-back"></div>
          <div class="glass-plane glass-plane-left"></div>
          <div class="glass-plane glass-plane-right"></div>

          <div class="shard-ui shard-ui-main">
            <div class="panel-topline">
              <span>01 / Selected build</span>
              <span class="panel-live"><i></i> Live systems</span>
            </div>
            <div class="panel-main">
              <p>Build clarity.</p>
              <h2>Thoughtful interfaces for ambitious ideas.</h2>
              <div class="panel-rule"></div>
              <div class="panel-stats">
                <div><span>Design</span><strong>Intent</strong></div>
                <div><span>Code</span><strong>Structure</strong></div>
              </div>
            </div>
          </div>

          <div class="shard-ui shard-ui-top">
            <span class="shard-label">System / 07</span>
            <strong>Break the ordinary.</strong>
            <span class="shard-detail">Sharp ideas, structured well.</span>
          </div>

          <div class="shard-ui shard-ui-side">
            <span class="shard-label">Signal</span>
            <div class="signal-bars"><i></i><i></i><i></i><i></i></div>
            <strong>Clarity</strong>
          </div>

          <div class="shard-ui shard-ui-bottom">
            <span>From concept</span>
            <strong>to impact.</strong>
          </div>

          <div class="glass-chip chip-index">2026</div>
          <div class="glass-shard shard-top"></div>
          <div class="glass-shard shard-bottom"></div>
          <div class="visual-crosshair crosshair-top"></div>
          <div class="visual-crosshair crosshair-bottom"></div>
        </div>
      </div>
    </div>

    <a class="scroll-prompt interactive" href="#about">
      <span class="scroll-line"></span>
      <span>Scroll to explore</span>
    </a>
  </section>
</template>

<script setup>
import { ref } from "vue";

const hero = ref(null);

const handlePointerMove = (event) => {
  if (!hero.value || !window.matchMedia("(pointer: fine)").matches) return;

  const rect = hero.value.getBoundingClientRect();
  const pointerX = (event.clientX - rect.left) / rect.width - 0.5;
  const pointerY = (event.clientY - rect.top) / rect.height - 0.5;

  hero.value.style.setProperty("--visual-x", `${pointerX * 12}px`);
  hero.value.style.setProperty("--visual-y", `${pointerY * 10}px`);
  hero.value.style.setProperty("--visual-rotate-x", `${pointerY * -4}deg`);
  hero.value.style.setProperty("--visual-rotate-y", `${pointerX * 5}deg`);
};

const resetPointer = () => {
  if (!hero.value) return;

  hero.value.style.setProperty("--visual-x", "0px");
  hero.value.style.setProperty("--visual-y", "0px");
  hero.value.style.setProperty("--visual-rotate-x", "0deg");
  hero.value.style.setProperty("--visual-rotate-y", "0deg");
};
</script>

<style scoped>
.hero {
  --visual-x: 0px;
  --visual-y: 0px;
  --visual-rotate-x: 0deg;
  --visual-rotate-y: 0deg;
  position: relative;
  isolation: isolate;
  overflow: hidden;
  min-height: max(44rem, 100svh);
  padding: clamp(8.2rem, 12vw, 10.5rem) 0 4rem;
  background:
    radial-gradient(circle at 75% 49%, rgba(226, 193, 106, 0.12), transparent 19rem),
    radial-gradient(circle at 4% 98%, rgba(124, 87, 21, 0.22), transparent 26rem),
    linear-gradient(122deg, #060706 0%, #0a0b0a 46%, #11110f 100%);
}

.hero::before,
.hero::after {
  position: absolute;
  z-index: -1;
  content: "";
  pointer-events: none;
}

.hero::before {
  inset: 0;
  background: linear-gradient(90deg, rgba(255, 255, 255, 0.035) 1px, transparent 1px);
  background-size: min(25vw, 24rem) 100%;
  opacity: 0.35;
  mask-image: linear-gradient(90deg, black, transparent 84%);
}

.hero::after {
  right: 0;
  bottom: 0;
  left: 0;
  height: 11rem;
  background: linear-gradient(transparent, var(--bg-primary));
}

.hero-shell {
  position: relative;
  z-index: 2;
  display: grid;
  grid-template-columns: minmax(0, 1.02fr) minmax(26rem, 0.98fr);
  gap: clamp(2.5rem, 7vw, 7.5rem);
  align-items: center;
}

.hero-copy {
  position: relative;
  z-index: 2;
  max-width: 43rem;
  animation: copy-enter 800ms cubic-bezier(0.2, 0.75, 0.2, 1) both;
}

.hero-eyebrow {
  display: flex;
  align-items: center;
  gap: 0.72rem;
  color: var(--gold-light);
  font-size: 0.69rem;
  font-weight: 700;
  letter-spacing: 0.18em;
  text-transform: uppercase;
}

.hero-eyebrow span {
  width: 2.7rem;
  height: 1px;
  background: currentColor;
}

.hero h1 {
  max-width: 9.6ch;
  margin-top: 1.25rem;
  color: #f6f5f1;
  font-size: clamp(3.25rem, 6.05vw, 6.15rem);
  font-weight: 600;
  letter-spacing: -0.078em;
  line-height: 0.91;
}

.hero h1 em {
  display: block;
  font-family: Georgia, "Times New Roman", serif;
  font-weight: 400;
  letter-spacing: -0.085em;
  color: var(--gold-light);
}

.hero-intro {
  max-width: 31rem;
  margin-top: 1.65rem;
  color: #b9b7af;
  font-size: clamp(0.95rem, 1.1vw, 1.06rem);
  line-height: 1.75;
}

.hero-actions {
  display: flex;
  flex-wrap: wrap;
  gap: 0.75rem;
  margin-top: 2.05rem;
}

.hero-button {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  gap: 0.7rem;
  min-height: 3.25rem;
  padding: 0.75rem 1.2rem;
  border: 1px solid transparent;
  border-radius: 999px;
  font-size: 0.82rem;
  font-weight: 700;
  letter-spacing: 0.01em;
  text-decoration: none;
  transition: transform 220ms ease, background-color 220ms ease, border-color 220ms ease,
    box-shadow 220ms ease;
}

.hero-button:hover,
.hero-button:focus-visible {
  transform: translateY(-2px);
}

.hero-button:focus-visible,
.scroll-prompt:focus-visible {
  outline: 2px solid var(--gold-light);
  outline-offset: 4px;
}

.hero-button-primary {
  background: linear-gradient(120deg, #e5cd82, #c39d42);
  color: #171308;
  box-shadow: 0 0.8rem 2.4rem rgba(192, 156, 66, 0.18);
}

.hero-button-primary:hover,
.hero-button-primary:focus-visible {
  box-shadow: 0 1.2rem 2.7rem rgba(192, 156, 66, 0.3);
}

.hero-button-secondary {
  border-color: rgba(232, 218, 178, 0.24);
  background: rgba(255, 255, 255, 0.025);
  color: #e5e0d6;
}

.hero-button-secondary:hover,
.hero-button-secondary:focus-visible {
  border-color: rgba(232, 218, 178, 0.54);
  background: rgba(255, 255, 255, 0.075);
}

.hero-meta {
  display: flex;
  flex-wrap: wrap;
  gap: 1.1rem 1.8rem;
  margin-top: clamp(2.9rem, 5vw, 4.75rem);
}

.hero-meta div {
  display: grid;
  gap: 0.27rem;
}

.hero-meta strong {
  color: rgba(229, 205, 130, 0.88);
  font-size: 0.63rem;
  font-weight: 700;
  letter-spacing: 0.14em;
}

.hero-meta span {
  color: #88877f;
  font-size: 0.72rem;
}

.hero-visual {
  position: relative;
  min-height: clamp(30rem, 48vw, 39rem);
  animation: visual-enter 1000ms cubic-bezier(0.2, 0.75, 0.2, 1) 120ms both;
  perspective: 1400px;
}

.visual-aura {
  position: absolute;
  inset: 8% -16% 0 -12%;
  border-radius: 50%;
  background: radial-gradient(ellipse, rgba(220, 184, 89, 0.14), transparent 65%);
  filter: blur(4px);
  opacity: 0.8;
}

.visual-system {
  position: absolute;
  inset: 0;
  transform: translate3d(var(--visual-x), var(--visual-y), 0)
    rotateX(var(--visual-rotate-x)) rotateY(var(--visual-rotate-y));
  transform-style: preserve-3d;
  transition: transform 280ms cubic-bezier(0.2, 0.75, 0.2, 1);
}

.fracture-map {
  position: absolute;
  z-index: 4;
  inset: 2.5% 0 0;
  width: 100%;
  height: 96%;
  overflow: visible;
  pointer-events: none;
}

.fracture-map path {
  stroke: rgba(246, 234, 198, 0.62);
  stroke-width: 1.15;
  vector-effect: non-scaling-stroke;
  filter: drop-shadow(0 0 4px rgba(234, 211, 144, 0.3));
}

.fracture-map circle {
  fill: #ead390;
  filter: drop-shadow(0 0 7px rgba(234, 211, 144, 0.9));
}

.glass-plane,
.glass-shard,
.shard-ui,
.glass-chip {
  position: absolute;
  overflow: hidden;
  border: 1px solid rgba(255, 249, 227, 0.18);
  background: linear-gradient(125deg, rgba(255, 255, 255, 0.19), rgba(255, 255, 255, 0.025) 45%, rgba(231, 191, 95, 0.08));
  box-shadow: inset 0 1px rgba(255, 255, 255, 0.18), 0 2.2rem 4.7rem rgba(0, 0, 0, 0.28);
  backdrop-filter: blur(15px) saturate(0.8);
  -webkit-backdrop-filter: blur(15px) saturate(0.8);
}

.glass-plane::after,
.glass-shard::after,
.shard-ui::before {
  position: absolute;
  content: "";
  pointer-events: none;
}

.glass-plane::after,
.glass-shard::after {
  inset: 0;
  background: linear-gradient(118deg, transparent 21%, rgba(255, 255, 255, 0.21) 36%, transparent 51%);
  opacity: 0.7;
  transform: translateX(-130%);
  animation: glint 8s ease-in-out infinite;
}

.glass-plane-back {
  z-index: 1;
  top: 6%;
  right: 6%;
  width: 78%;
  height: 62%;
  clip-path: polygon(19% 0, 100% 10%, 87% 77%, 28% 100%, 0 55%);
  opacity: 0.58;
  transform: rotate(7deg) translateZ(-20px);
}

.glass-plane-left {
  z-index: 3;
  bottom: 4%;
  left: -3%;
  width: 42%;
  height: 48%;
  clip-path: polygon(0 7%, 100% 0, 76% 77%, 16% 100%);
  opacity: 0.8;
  transform: rotate(-5deg) translateZ(16px);
}

.glass-plane-right {
  z-index: 2;
  right: -2%;
  bottom: 2%;
  width: 34%;
  height: 44%;
  clip-path: polygon(25% 0, 100% 32%, 89% 100%, 0 76%);
  background: linear-gradient(145deg, rgba(230, 194, 105, 0.14), rgba(255, 255, 255, 0.04));
  opacity: 0.72;
  transform: rotate(10deg) translateZ(-6px);
}

.shard-ui {
  z-index: 5;
  color: #f1eee5;
  transform: translateZ(32px);
}

.shard-ui::before {
  inset: 0;
  background: linear-gradient(
    120deg,
    rgba(255, 255, 255, 0.15),
    transparent 28%,
    transparent 70%,
    rgba(239, 211, 131, 0.08)
  );
}

.shard-ui-main {
  top: 20%;
  right: 11%;
  width: min(68%, 23rem);
  height: 51%;
  min-height: 16.5rem;
  padding: clamp(1.2rem, 2.6vw, 1.85rem);
  clip-path: polygon(13% 0, 100% 8%, 85% 100%, 0 82%);
  background:
    radial-gradient(circle at 85% 10%, rgba(238, 208, 123, 0.2), transparent 22%),
    linear-gradient(135deg, rgba(35, 36, 31, 0.88), rgba(18, 19, 17, 0.68));
}

.shard-ui-top {
  top: 6%;
  right: 7%;
  display: grid;
  gap: 0.34rem;
  width: 42%;
  min-height: 7.2rem;
  padding: 1.1rem 1.2rem 1.4rem;
  clip-path: polygon(14% 0, 100% 17%, 88% 100%, 0 73%);
  background: linear-gradient(132deg, rgba(45, 45, 37, 0.86), rgba(23, 23, 20, 0.74));
  transform: translateZ(22px) rotate(2deg);
}

.shard-ui-side {
  bottom: 11%;
  left: 6%;
  display: grid;
  align-content: center;
  gap: 0.72rem;
  width: 32%;
  min-height: 8.75rem;
  padding: 1.2rem 1rem 1.25rem 1.45rem;
  clip-path: polygon(0 8%, 100% 0, 76% 100%, 13% 83%);
  background: linear-gradient(144deg, rgba(57, 54, 42, 0.86), rgba(21, 21, 18, 0.76));
  transform: translateZ(44px) rotate(-5deg);
}

.shard-ui-bottom {
  right: 5%;
  bottom: 0;
  display: grid;
  gap: 0.14rem;
  width: 38%;
  min-height: 5.65rem;
  padding: 1.25rem 1.15rem 1rem;
  clip-path: polygon(22% 0, 100% 25%, 74% 100%, 0 79%);
  background: linear-gradient(134deg, rgba(58, 52, 37, 0.8), rgba(20, 20, 17, 0.76));
  transform: translateZ(54px) rotate(4deg);
}

.shard-label,
.shard-detail {
  position: relative;
  z-index: 1;
  color: rgba(232, 217, 177, 0.66);
  font-size: 0.54rem;
  font-weight: 700;
  letter-spacing: 0.13em;
  text-transform: uppercase;
}

.shard-ui-top strong,
.shard-ui-side strong,
.shard-ui-bottom strong,
.shard-ui-bottom span {
  position: relative;
  z-index: 1;
}

.shard-ui-top strong {
  max-width: 9ch;
  color: #eee8d9;
  font-size: clamp(1rem, 1.75vw, 1.3rem);
  font-weight: 500;
  letter-spacing: -0.055em;
  line-height: 0.96;
}

.shard-ui-side strong {
  color: #e8d180;
  font-family: Georgia, "Times New Roman", serif;
  font-size: 1.28rem;
  font-style: italic;
  font-weight: 400;
}

.shard-ui-bottom span {
  color: #9c998e;
  font-size: 0.62rem;
  letter-spacing: 0.08em;
}

.shard-ui-bottom strong {
  color: #eee7d6;
  font-size: 0.9rem;
  font-weight: 600;
  letter-spacing: -0.04em;
}

.signal-bars {
  position: relative;
  z-index: 1;
  display: flex;
  align-items: end;
  gap: 0.22rem;
  height: 1.8rem;
}

.signal-bars i {
  display: block;
  width: 0.22rem;
  background: linear-gradient(#ead28b, rgba(234, 210, 139, 0.26));
}

.signal-bars i:nth-child(1) { height: 34%; }
.signal-bars i:nth-child(2) { height: 66%; }
.signal-bars i:nth-child(3) { height: 46%; }
.signal-bars i:nth-child(4) { height: 100%; }

.panel-topline,
.panel-main {
  position: relative;
  z-index: 1;
}

.panel-topline {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 1rem;
  color: rgba(228, 217, 181, 0.75);
  font-size: 0.57rem;
  font-weight: 700;
  letter-spacing: 0.125em;
  text-transform: uppercase;
}

.panel-live {
  display: inline-flex;
  align-items: center;
  gap: 0.38rem;
  color: #e2c670;
}

.panel-live i {
  width: 0.34rem;
  height: 0.34rem;
  border-radius: 50%;
  background: #d7bc5f;
  box-shadow: 0 0 0 0.28rem rgba(215, 188, 95, 0.11);
}

.panel-main {
  display: flex;
  flex-direction: column;
  height: calc(100% - 1.2rem);
  padding-top: clamp(2.6rem, 5vw, 4.6rem);
}

.panel-main p {
  color: #e5cb7d;
  font-family: Georgia, "Times New Roman", serif;
  font-size: clamp(1.25rem, 2.4vw, 1.8rem);
  font-style: italic;
}

.panel-main h2 {
  max-width: 11ch;
  margin-top: 0.4rem;
  color: #f1eee5;
  font-size: clamp(1.35rem, 2.45vw, 2.05rem);
  font-weight: 500;
  letter-spacing: -0.065em;
  line-height: 0.98;
}

.panel-rule {
  width: 100%;
  height: 1px;
  margin-top: auto;
  background: linear-gradient(90deg, rgba(229, 203, 125, 0.75), rgba(229, 203, 125, 0.08));
}

.panel-stats {
  display: flex;
  gap: 2rem;
  padding-top: 0.9rem;
}

.panel-stats div {
  display: grid;
  gap: 0.22rem;
}

.panel-stats span {
  color: #96948d;
  font-size: 0.59rem;
  letter-spacing: 0.08em;
  text-transform: uppercase;
}

.panel-stats strong {
  color: #e6e1d3;
  font-size: 0.72rem;
  font-weight: 600;
}

.glass-chip {
  z-index: 6;
  display: inline-flex;
  align-items: center;
  gap: 0.55rem;
  color: #e8e1ce;
  font-size: 0.66rem;
  letter-spacing: 0.05em;
  transform: translateZ(48px);
}

.chip-index {
  top: 6%;
  left: 4%;
  justify-content: center;
  width: 4.1rem;
  height: 3rem;
  clip-path: polygon(0 0, 100% 17%, 82% 100%, 10% 79%);
  color: #e2c670;
  font-size: 0.66rem;
  font-weight: 700;
  letter-spacing: 0.14em;
}

.glass-shard {
  z-index: 5;
  background: linear-gradient(125deg, rgba(255, 255, 255, 0.2), rgba(226, 190, 98, 0.07));
  transform: translateZ(56px);
}

.shard-top {
  top: 4%;
  right: 2%;
  width: 9rem;
  height: 6.3rem;
  clip-path: polygon(12% 0, 100% 20%, 79% 100%, 0 64%);
  animation-delay: -2.8s;
}

.shard-bottom {
  right: 14%;
  bottom: -1%;
  width: 6.6rem;
  height: 5.3rem;
  clip-path: polygon(21% 0, 100% 16%, 75% 100%, 0 72%);
  animation-delay: -5.6s;
}

.visual-crosshair {
  position: absolute;
  z-index: 7;
  width: 1.75rem;
  height: 1.75rem;
  border: 1px solid rgba(239, 216, 146, 0.48);
  border-radius: 50%;
  transform: translateZ(60px);
}

.visual-crosshair::before,
.visual-crosshair::after {
  position: absolute;
  top: 50%;
  left: 50%;
  width: 2.45rem;
  height: 1px;
  content: "";
  background: rgba(239, 216, 146, 0.35);
  transform: translate(-50%, -50%);
}

.visual-crosshair::after {
  transform: translate(-50%, -50%) rotate(90deg);
}

.crosshair-top {
  top: 25%;
  left: 8%;
}

.crosshair-bottom {
  right: 2%;
  bottom: 24%;
  transform: scale(0.62) translateZ(60px);
}

.hero-grid {
  position: absolute;
  z-index: -1;
  inset: 0;
  pointer-events: none;
  background-image: linear-gradient(rgba(234, 211, 144, 0.075) 1px, transparent 1px),
    linear-gradient(90deg, rgba(234, 211, 144, 0.075) 1px, transparent 1px);
  background-position: center;
  background-size: 6rem 6rem;
  mask-image: radial-gradient(ellipse at 72% 50%, black, transparent 67%);
  opacity: 0.48;
}

.hero-grain {
  position: absolute;
  z-index: -1;
  inset: 0;
  pointer-events: none;
  opacity: 0.035;
  background-image: url("data:image/svg+xml,%3Csvg viewBox='0 0 180 180' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='.9' numOctaves='4' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23n)' opacity='.7'/%3E%3C/svg%3E");
}

.hero-halo {
  position: absolute;
  z-index: -1;
  width: 22rem;
  height: 22rem;
  border: 1px solid rgba(232, 207, 133, 0.075);
  border-radius: 50%;
  pointer-events: none;
}

.halo-left {
  top: 15%;
  left: -14rem;
}

.halo-right {
  right: -12rem;
  bottom: -12rem;
  width: 35rem;
  height: 35rem;
}

.scroll-prompt {
  position: absolute;
  z-index: 3;
  bottom: 1.45rem;
  left: max(1.25rem, calc((100vw - 90rem) / 2 + 1.5rem));
  display: inline-flex;
  align-items: center;
  gap: 0.65rem;
  color: #99978e;
  font-size: 0.63rem;
  font-weight: 700;
  letter-spacing: 0.14em;
  text-decoration: none;
  text-transform: uppercase;
  transition: color 200ms ease;
}

.scroll-prompt:hover {
  color: var(--gold-light);
}

.scroll-line {
  display: block;
  width: 2rem;
  height: 1px;
  background: currentColor;
}

@keyframes copy-enter {
  from {
    opacity: 0;
    transform: translateY(1.5rem);
  }
}

@keyframes visual-enter {
  from {
    opacity: 0;
    transform: translate3d(1.4rem, 1rem, 0) scale(0.96);
  }
}

@keyframes glint {
  15%,
  100% {
    transform: translateX(130%);
  }
}

@media (min-width: 1536px) {
  .scroll-prompt {
    left: clamp(6rem, 7vw, 13.75rem);
  }
}

@media (max-width: 1023px) {
  .hero {
    min-height: auto;
    padding-bottom: 5.2rem;
  }

  .hero-shell {
    grid-template-columns: 1fr;
    gap: 2rem;
  }

  .hero-copy {
    max-width: 42rem;
  }

  .hero-visual {
    width: min(100%, 39rem);
    min-height: 33rem;
    margin: -1rem auto 0;
  }

  .scroll-prompt {
    display: none;
  }
}

@media (max-width: 640px) {
  .hero {
    min-height: auto;
    padding-top: 7.7rem;
    padding-bottom: 2.4rem;
  }

  .hero h1 {
    max-width: 9.4ch;
    font-size: clamp(3.1rem, 15vw, 4.15rem);
  }

  .hero-intro {
    max-width: 31ch;
  }

  .hero-meta {
    gap: 0.9rem 1.15rem;
    margin-top: 2.7rem;
  }

  .hero-meta div:last-child {
    display: none;
  }

  .hero-visual {
    min-height: 26.5rem;
    margin-top: -0.5rem;
  }

  .shard-ui-main {
    top: 20%;
    right: 5%;
    width: 82%;
    height: 56%;
    min-height: 15rem;
  }

  .shard-ui-top {
    top: 6%;
    right: 3%;
    width: 45%;
    min-height: 6.2rem;
    padding: 0.95rem 1rem 1.2rem;
  }

  .shard-ui-side {
    bottom: 10%;
    left: 2%;
    width: 35%;
    min-height: 8rem;
  }

  .shard-ui-bottom {
    right: 1%;
    bottom: 0;
    width: 41%;
    min-height: 5rem;
    padding: 1rem 0.9rem 0.75rem;
  }

  .panel-main {
    padding-top: 2.7rem;
  }

  .glass-plane-back {
    right: 0;
    width: 86%;
  }

  .glass-plane-left {
    left: -7%;
    width: 47%;
  }

  .glass-plane-right,
  .shard-top,
  .crosshair-bottom {
    display: none;
  }

  .chip-index {
    top: 4%;
    left: 2%;
  }

  .shard-bottom {
    right: 7%;
    bottom: 4%;
  }

  .crosshair-top {
    top: 21%;
    left: 4%;
  }
}

@media (prefers-reduced-motion: reduce) {
  .hero-copy,
  .hero-visual,
  .glass-plane::after,
  .glass-shard::after {
    animation: none;
  }

  .visual-system {
    transition: none;
  }
}
</style>

// src/views/Hero.jsx
"use client";

import { useEffect, useRef, useState } from "react";
import { motion, useReducedMotion, useScroll, useSpring, useTransform } from "motion/react";

const containerClass = "mx-auto w-full max-w-[90rem] px-5 sm:px-8 md:px-12 lg:px-20 2xl:max-w-none 2xl:px-[clamp(6rem,7vw,13.75rem)]";

const sequence = [
  { key: "eyebrow", text: "Available for new projects", speed: 28 },
  { key: "headline", text: "Full-stack.\nBuilt to ship.", speed: 24 },
  { key: "role", text: "Currently shipping interfaces", speed: 34 },
];

const completeText = Object.fromEntries(sequence.map(({ key, text }) => [key, text]));

function TypedSegments({ value, segments }) {
  let offset = 0;

  return segments.map(({ text, className = "" }, index) => {
    const visible = value.slice(offset, offset + text.length);
    offset += text.length;

    if (!visible) return null;

    return (
      <span className={className} key={`${text}-${index}`}>
        {visible}
      </span>
    );
  });
}

function usePieceMotion(assembly, reduceMotion, start, duration, from, to = {}) {
  const progress = useTransform(assembly, [start, Math.min(start + duration, 1)], [0, 1]);
  const initial = reduceMotion ? {} : from;

  return {
    x: useTransform(progress, [0, 1], [initial.x ?? to.x ?? 0, to.x ?? 0]),
    y: useTransform(progress, [0, 1], [initial.y ?? to.y ?? 0, to.y ?? 0]),
    rotate: useTransform(progress, [0, 1], [initial.rotate ?? to.rotate ?? 0, to.rotate ?? 0]),
    scale: useTransform(progress, [0, 1], [initial.scale ?? to.scale ?? 1, to.scale ?? 1]),
    opacity: useTransform(progress, [0, 1], [initial.opacity ?? to.opacity ?? 1, to.opacity ?? 1]),
  };
}

function SourceGlassVisual({ assembly, reduceMotion }) {
  const main = usePieceMotion(assembly, reduceMotion, 0, 0.14, { y: 18, scale: 0.94, opacity: 0.88 }, { opacity: 1 });
  const back = usePieceMotion(assembly, reduceMotion, 0.06, 0.24, { x: 45, y: -29, scale: 0.84, opacity: 0.24 }, { opacity: 0.58 });
  const top = usePieceMotion(assembly, reduceMotion, 0.1, 0.2, { x: 38, y: -37, scale: 0.82, opacity: 0.38 }, { opacity: 1 });
  const left = usePieceMotion(assembly, reduceMotion, 0.14, 0.24, { x: -53, y: 29, scale: 0.82, opacity: 0.3 }, { opacity: 0.8 });
  const side = usePieceMotion(assembly, reduceMotion, 0.2, 0.24, { x: -40, y: 29, scale: 0.84, opacity: 0.38 }, { opacity: 1 });
  const right = usePieceMotion(assembly, reduceMotion, 0.25, 0.24, { x: 51, y: 26, scale: 0.8, opacity: 0.3 }, { opacity: 0.72 });
  const chip = usePieceMotion(assembly, reduceMotion, 0.28, 0.2, { x: -32, y: -29, scale: 0.78, opacity: 0.34 }, { opacity: 1 });
  const bottom = usePieceMotion(assembly, reduceMotion, 0.32, 0.2, { x: 38, y: 32, scale: 0.82, opacity: 0.34 }, { opacity: 1 });
  const shard = usePieceMotion(assembly, reduceMotion, 0.35, 0.28, { x: 32, y: -22, scale: 0.8, opacity: 0.3 }, { opacity: 1 });
  const crosshair = usePieceMotion(assembly, reduceMotion, 0.25, 0.3, { x: -16, y: 19, opacity: 0.3 }, { opacity: 1 });
  const fractureOpacity = useTransform(assembly, [0.04, 0.56], [0.46, 1]);

  return (
    <div className="relative mx-auto w-full max-w-[31rem] animate-[hero-reveal_0.9s_ease-out_both] lg:mx-0" aria-hidden="true">
      <div className="hero-solid-visual">
        <div className="hero-solid-aura" />
        <div className="hero-solid-beam hero-solid-beam-one" />
        <div className="hero-solid-beam hero-solid-beam-two" />

        <div className="hero-solid-system">
          <motion.svg className="hero-solid-fracture-map" viewBox="0 0 600 620" fill="none" preserveAspectRatio="none" style={{ opacity: fractureOpacity }}>
            <path d="M31 48L230 205L184 389L468 574" />
            <path d="M230 205L526 62" />
            <path d="M230 205L449 302L578 456" />
            <path d="M184 389L18 495" />
            <path d="M184 389L349 498L543 608" />
            <path d="M449 302L493 175" />
            <path d="M349 498L394 616" />
            <circle cx="230" cy="205" r="5" />
            <circle cx="184" cy="389" r="4" />
          </motion.svg>

          <motion.div className="hero-solid-glass-plane hero-solid-glass-plane-back" style={back} />
          <motion.div className="hero-solid-glass-plane hero-solid-glass-plane-left" style={left} />
          <motion.div className="hero-solid-glass-plane hero-solid-glass-plane-right" style={right} />

          <motion.div className="hero-solid-shard-ui hero-solid-shard-ui-main" style={main}>
            <div className="hero-solid-panel-topline"><span className="hero-solid-panel-live"><i /> Live</span></div>
            <div className="hero-solid-panel-main">
              <p>Clear.</p>
              <h2>Ship it.</h2>
              <div className="hero-solid-panel-rule" />
              <div className="hero-solid-panel-stats">
                <div><span>Design</span><strong>Clear</strong></div>
                <div><span>Code</span><strong>Solid</strong></div>
              </div>
            </div>
          </motion.div>

          <motion.div className="hero-solid-shard-ui hero-solid-shard-ui-top" style={top}>
            <strong>Make it clear.</strong>
            <span className="hero-solid-shard-detail">Built to last.</span>
          </motion.div>

          <motion.div className="hero-solid-shard-ui hero-solid-shard-ui-side" style={side}>
            <span className="hero-solid-shard-label">Signal</span>
            <div className="hero-solid-signal-bars"><i /><i /><i /><i /></div>
            <strong>Clarity</strong>
          </motion.div>

          <motion.div className="hero-solid-shard-ui hero-solid-shard-ui-bottom" style={bottom}>
            <span>From idea</span>
            <strong>To shipped.</strong>
          </motion.div>

          <motion.div className="hero-solid-glass-shard hero-solid-shard-top" style={shard} />
          <motion.div className="hero-solid-glass-shard hero-solid-shard-bottom" style={shard} />
          <motion.div className="hero-solid-visual-crosshair hero-solid-crosshair-bottom" style={crosshair} />
        </div>
      </div>

    </div>
  );
}

const ambientShards = [
  { left: "3.5%", top: "9%", width: "3.2rem", height: "1.5rem", clipPath: "polygon(13% 0, 100% 17%, 81% 100%, 0 76%)", travelX: "63vw", travelY: "30svh", start: 0, rotate: -21 },
  { left: "30%", top: "17%", width: "1.25rem", height: "3.5rem", clipPath: "polygon(0 12%, 82% 0, 100% 86%, 20% 100%)", travelX: "38vw", travelY: "21svh", start: 0.04, rotate: 18 },
  { left: "4%", top: "56%", width: "2rem", height: "2.8rem", clipPath: "polygon(4% 0, 100% 22%, 78% 100%, 0 76%)", travelX: "61vw", travelY: "-14svh", start: 0.08, rotate: 28 },
  { left: "auto", right: "7%", top: "auto", bottom: "12%", width: "3.1rem", height: "1.25rem", clipPath: "polygon(13% 0, 100% 17%, 81% 100%, 0 76%)", travelX: "-24vw", travelY: "-28svh", start: 0.12, rotate: -14 },
  { left: "44%", top: "78%", width: "1.45rem", height: "3rem", clipPath: "polygon(0 12%, 82% 0, 100% 86%, 20% 100%)", travelX: "25vw", travelY: "-26svh", start: 0.02, rotate: 32 },
  { left: "auto", right: "5%", top: "16%", width: "1.5rem", height: "2.2rem", clipPath: "polygon(13% 0, 100% 17%, 81% 100%, 0 76%)", travelX: "-18vw", travelY: "22svh", start: 0.1, rotate: -31 },
  { left: "auto", right: "3%", top: "48%", width: "2.7rem", height: "1.2rem", clipPath: "polygon(13% 0, 100% 17%, 81% 100%, 0 76%)", travelX: "-23vw", travelY: "0svh", start: 0.06, rotate: 16 },
  { left: "59%", top: "7%", width: "2.2rem", height: "1.1rem", clipPath: "polygon(13% 0, 100% 17%, 81% 100%, 0 76%)", travelX: "11vw", travelY: "32svh", start: 0.14, rotate: 25 },
  { left: "8%", top: "72%", width: "1.1rem", height: "1.1rem", clipPath: "polygon(13% 0, 100% 17%, 81% 100%, 0 76%)", travelX: "60vw", travelY: "-24svh", start: 0.1, rotate: -18 },
];

function AmbientGlassFragments({ assembly, reduceMotion }) {
  return (
    <div className="pointer-events-none absolute inset-0 z-[2] hidden lg:block" aria-hidden="true">
      {ambientShards.map((shard) => <AmbientGlassShard key={`${shard.left}-${shard.top}`} shard={shard} assembly={assembly} reduceMotion={reduceMotion} />)}
    </div>
  );
}

function AmbientGlassShard({ shard, assembly, reduceMotion }) {
  const end = Math.min(shard.start + 0.58, 1);
  const x = useTransform(assembly, [shard.start, end], ["0px", reduceMotion ? "0px" : shard.travelX]);
  const y = useTransform(assembly, [shard.start, end], ["0px", reduceMotion ? "0px" : shard.travelY]);
  const scale = useTransform(assembly, [shard.start, end], [1, reduceMotion ? 1 : 0.78]);
  const opacity = useTransform(assembly, [shard.start, end], reduceMotion ? [0, 0] : [0.9, 0.66]);

  return (
    <motion.div
      className="absolute"
      style={{ left: shard.left, right: shard.right, top: shard.top, bottom: shard.bottom, width: shard.width, height: shard.height, x, y, scale, rotate: shard.rotate, opacity }}
    >
      <div className="hero-source-scatter-piece" style={{ clipPath: shard.clipPath }} />
    </motion.div>
  );
}

export default function Hero() {
  const [typed, setTyped] = useState({ eyebrow: "", headline: "", role: "" });
  const [phase, setPhase] = useState(0);
  const sceneRef = useRef(null);
  const reduceMotion = useReducedMotion();
  const { scrollYProgress: sceneScrollProgress } = useScroll({ target: sceneRef, offset: ["start start", "end start"] });
  const smoothSceneProgress = useSpring(sceneScrollProgress, { stiffness: 180, damping: 36, mass: 0.45 });
  const assembly = useTransform(smoothSceneProgress, [0, 0.7, 1], reduceMotion ? [1, 1, 1] : [0, 0.9, 1]);

  const downloadResume = () => {
    window.location.assign("/resume");
  };

  const isReady = phase >= sequence.length;

  useEffect(() => {
    let active = true;
    let intervalId = null;
    let timeoutId = null;

    const showEverything = () => {
      setTyped(completeText);
      setPhase(sequence.length);
    };

    if (window.matchMedia("(prefers-reduced-motion: reduce)").matches) {
      showEverything();
      return () => undefined;
    }

    const typeNext = (index) => {
      if (!active) return;

      if (index >= sequence.length) {
        setPhase(sequence.length);
        return;
      }

      const item = sequence[index];
      let characterIndex = 0;
      setPhase(index);

      intervalId = window.setInterval(() => {
        if (!active) return;

        characterIndex += 1;
        setTyped((current) => ({
          ...current,
          [item.key]: item.text.slice(0, characterIndex),
        }));

        if (characterIndex >= item.text.length) {
          window.clearInterval(intervalId);
          timeoutId = window.setTimeout(() => typeNext(index + 1), 150);
        }
      }, item.speed);
    };

    typeNext(0);

    return () => {
      active = false;
      if (intervalId) window.clearInterval(intervalId);
      if (timeoutId) window.clearTimeout(timeoutId);
    };
  }, []);

  const headlineSegments = [
    { text: "Full-stack.\n", className: "text-amber" },
    { text: "Built to ship.", className: "text-copy" },
  ];

  return (
    <section ref={sceneRef} className="relative isolate min-h-[100svh] overflow-x-clip bg-ink/90 font-mono text-left lg:h-[170svh]">
      <div className="relative flex min-h-[100svh] items-center overflow-hidden pb-12 pt-[clamp(7.4rem,11vw,10rem)] lg:sticky lg:top-0">
        <div className="pointer-events-none absolute -right-24 top-[13%] -z-10 size-[min(42rem,66vw)] rounded-full bg-[radial-gradient(ellipse,rgba(212,175,55,0.15),transparent_68%)] blur-2xl" aria-hidden="true" />
        <div className="pointer-events-none absolute right-[5%] top-[10%] -z-10 hidden select-none font-mono text-[clamp(18rem,38vw,38rem)] font-black leading-none tracking-[-0.18em] text-white/[0.025] lg:block" aria-hidden="true">EL</div>
        <AmbientGlassFragments assembly={assembly} reduceMotion={reduceMotion} />

        <div className={`${containerClass} relative z-10`}>
        <div className="mb-8 flex items-center gap-4 text-[0.6rem] font-semibold uppercase tracking-[0.14em] text-muted sm:mb-10">
          <div className="flex items-center gap-2 text-amber">
            <span className="size-1.5 animate-[status-pulse_2s_ease-in-out_infinite] rounded-full bg-amber shadow-[0_0_0.65rem_0.12rem_rgba(212,175,55,0.7)]" aria-hidden="true" />
            <span>{typed.eyebrow}</span>
            {phase === 0 ? <span className="animate-[cursor-blink_1s_step-end_infinite] text-cyan" aria-hidden="true">_</span> : null}
          </div>
        </div>

        <div className="grid items-center gap-14 lg:grid-cols-[minmax(0,1fr)_minmax(22rem,0.78fr)] lg:gap-[clamp(4rem,9vw,10rem)]">
          <div className="lg:-translate-y-8 2xl:-translate-y-12">
            <p className="mb-5 flex items-center gap-3 text-[0.68rem] font-semibold uppercase tracking-[0.16em] text-muted">
              <span className="h-px w-8 bg-amber" aria-hidden="true" />
              Software engineer / product builder
            </p>

            <h1 className="relative min-h-[2.08em] max-w-[24ch] text-[clamp(1.7rem,5vw,4.65rem)] font-bold leading-[1.04] tracking-[-0.07em] text-copy">
              <span className="invisible block whitespace-pre-line" aria-hidden="true">{completeText.headline}</span>
              <span className="absolute inset-x-0 top-0 whitespace-pre-line">
                <TypedSegments value={typed.headline} segments={headlineSegments} />
                {phase === 1 ? <span className="animate-[cursor-blink_1s_step-end_infinite] text-cyan" aria-hidden="true">_</span> : null}
              </span>
            </h1>

            <p className="mt-7 min-h-6 text-[clamp(0.84rem,1.35vw,1rem)] leading-normal text-muted">
              {typed.role}
              {phase === 2 ? <span className="animate-[cursor-blink_1s_step-end_infinite] text-cyan" aria-hidden="true">_</span> : null}
            </p>

            <div className={`mt-8 flex flex-wrap gap-3 transition duration-500 ${isReady ? "translate-y-0 opacity-100" : "pointer-events-none translate-y-2 opacity-0"}`}>
              <a href="#works" className="inline-flex min-h-12 items-center gap-2 rounded-full bg-amber px-6 py-3 text-[0.72rem] font-bold text-ink shadow-[0_0_2rem_rgba(212,175,55,0.16)] transition hover:-translate-y-1 hover:bg-amber-light focus-visible:outline-2 focus-visible:outline-offset-3 focus-visible:outline-cyan">
                View selected work <span aria-hidden="true">↗</span>
              </a>
              <a href="#contact" className="inline-flex min-h-12 items-center rounded-full border border-white/15 bg-white/[0.03] px-6 py-3 text-[0.72rem] font-bold text-copy backdrop-blur-sm transition hover:-translate-y-1 hover:border-cyan hover:text-cyan focus-visible:outline-2 focus-visible:outline-offset-3 focus-visible:outline-cyan">
                Start a project
              </a>
            </div>

            <div className={`mt-11 flex flex-wrap items-center gap-x-8 gap-y-4 border-t border-white/10 pt-5 transition duration-500 ${isReady ? "translate-y-0 opacity-100" : "pointer-events-none translate-y-2 opacity-0"}`}>
              <div className="grid gap-1">
                <strong className="font-mono text-xl font-semibold tracking-[-0.06em] text-copy">4+</strong>
                <span className="text-[0.6rem] uppercase tracking-[0.1em] text-muted">years shipping</span>
              </div>
              <div className="grid gap-1">
                <strong className="font-mono text-xl font-semibold tracking-[-0.06em] text-copy">20+</strong>
                <span className="text-[0.6rem] uppercase tracking-[0.1em] text-muted">products built</span>
              </div>
              <div className="grid gap-1">
                <strong className="font-mono text-xl font-semibold tracking-[-0.06em] text-copy">∞</strong>
                <span className="text-[0.6rem] uppercase tracking-[0.1em] text-muted">curiosity</span>
              </div>
              <button type="button" onClick={downloadResume} className="inline-flex min-h-10 cursor-pointer items-center rounded-full border border-amber/50 bg-amber/10 px-4 py-2 text-[0.66rem] font-bold text-amber transition hover:-translate-y-0.5 hover:bg-amber hover:text-ink focus-visible:outline-2 focus-visible:outline-offset-3 focus-visible:outline-cyan">
                Download résumé
              </button>
            </div>
          </div>

          <div className="lg:-translate-y-8 2xl:-translate-y-12">
            <SourceGlassVisual assembly={assembly} reduceMotion={reduceMotion} />
          </div>
        </div>
        </div>
      </div>
    </section>
  );
}
