// src/views/Skills.jsx
import {
  siConfluence,
  siGit,
  siGithub,
  siJira,
  siMedusa,
  siNodedotjs,
  siNestjs,
  siNextdotjs,
  siReact,
  siSpringboot,
  siVuedotjs,
} from "simple-icons";
import Reveal from "../components/Reveal";

const containerClass = "mx-auto w-full max-w-[90rem] px-5 sm:px-8 md:px-12 lg:px-20 2xl:max-w-none 2xl:px-[clamp(6rem,7vw,13.75rem)]";

const skills = [
  { name: "Vue", icon: siVuedotjs, color: "#42b883" },
  { name: "React", icon: siReact, color: "#61dafb" },
  { name: "Next.js", icon: siNextdotjs, color: "#f5f5f5" },
  { name: "React Native", icon: siReact, color: "#61dafb" },
  { name: "Node.js", icon: siNodedotjs, color: "#8cc84b" },
  { name: "NestJS", icon: siNestjs, color: "#e0234e" },
  { name: "Spring Boot", icon: siSpringboot, color: "#6db33f" },
  { name: "Medusa.js", icon: siMedusa, color: "#e6cb77" },
  { name: "Git", icon: siGit, color: "#f05032" },
  { name: "GitHub", icon: siGithub, color: "#f5f5f5" },
  { name: "Jira", icon: siJira, color: "#579dff" },
  { name: "Confluence", icon: siConfluence, color: "#7c9cff" },
];

export default function Skills() {
  return (
    <section className="relative overflow-hidden bg-ink py-[4.5rem]">
      <div className={containerClass}>
        <Reveal>
          <p className="m-0 text-xs font-bold uppercase tracking-[0.14em] text-amber">Toolkit</p>
          <h2 className="mt-3 text-[clamp(1.9rem,3.4vw,3rem)] font-semibold leading-none tracking-[-0.06em] text-copy">Core stack.</h2>
        </Reveal>

        <div className="mt-7 grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-4 xl:grid-cols-6" role="list" aria-label="Core technologies and tools">
          {skills.map((skill, index) => (
            <Reveal key={skill.name} delay={index * 0.045} direction={index % 2 === 0 ? "up" : "left"}>
              <div className="flex min-h-20 cursor-pointer items-center gap-3 rounded-2xl border border-amber/15 bg-gradient-to-br from-white/[0.08] to-panel-alt/90 px-3 py-3 text-xs font-semibold text-copy transition hover:-translate-y-1 hover:border-amber/50" role="listitem">
                <span className="inline-flex size-9 shrink-0 items-center justify-center rounded-xl border border-white/15 bg-ink/70 text-[var(--icon-color)]" style={{ "--icon-color": skill.color }}>
                  <svg className="size-[1.1rem] fill-current" viewBox="0 0 24 24" aria-hidden="true"><path d={skill.icon.path} /></svg>
                </span>
                <span>{skill.name}</span>
              </div>
            </Reveal>
          ))}
        </div>
      </div>
    </section>
  );
}

// src/views/Skills.vue
<template>
  <section class="skills">
    <div class="skills-shell site-container">
      <div class="skills-heading">
        <div>
          <p class="skills-eyebrow">Toolkit</p>
          <h2 class="skills-title">Core stack.</h2>
        </div>
        <p class="skills-text">Tools for clear interfaces and dependable systems.</p>
      </div>

      <div class="skills-frame">
        <div class="skills-marquee" aria-label="Technology stack" role="list">
          <div class="skills-track">
            <div
              v-for="copy in 3"
              :key="copy"
              class="skills-group"
              :aria-hidden="copy > 1"
            >
              <div
                v-for="skill in skills"
                :key="`${copy}-${skill.name}`"
                class="skill-pill"
                role="listitem"
              >
                <span
                  class="skill-mark"
                  :class="`skill-mark-${skill.slug}`"
                  :style="skill.icon ? { '--icon-color': `#${skill.icon.hex}` } : {}"
                >
                  <img
                    v-if="skill.image"
                    :src="skill.image"
                    :alt="`${skill.name} logo`"
                    class="skill-icon skill-icon-image"
                  />
                  <svg
                    v-else
                    class="skill-icon"
                    viewBox="0 0 24 24"
                    aria-hidden="true"
                  >
                    <path :d="skill.icon.path" />
                  </svg>
                </span>
                <span>{{ skill.name }}</span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</template>

<script setup>
import {
  siGit,
  siJira,
  siNodedotjs,
  siNextdotjs,
  siReact,
  siSpringboot,
  siVuedotjs,
} from "simple-icons";

const skills = [
  { name: "Vue", slug: "vue", icon: siVuedotjs },
  { name: "React", slug: "react", icon: siReact },
  { name: "Next.js", slug: "next", icon: siNextdotjs },
  { name: "React Native", slug: "native", icon: siReact },
  { name: "Node.js", slug: "node", icon: siNodedotjs },
  { name: "Spring Boot", slug: "spring", icon: siSpringboot },
  { name: "Git", slug: "git", icon: siGit },
  { name: "Jira", slug: "jira", icon: siJira },
];

</script>

<style scoped>
.skills {
  position: relative;
  overflow: hidden;
  padding: 4.5rem 0;
  background: var(--bg-primary);
}

.skills-shell {
  position: relative;
  z-index: 1;
  animation: skills-rise 700ms cubic-bezier(0.2, 0.75, 0.2, 1) 100ms both;
}

.skills-heading {
  display: flex;
  align-items: end;
  justify-content: space-between;
  gap: 2rem;
}

.skills-eyebrow {
  color: var(--gold);
  font-size: 0.72rem;
  font-weight: 700;
  letter-spacing: 0.14em;
  text-transform: uppercase;
}

.skills-title {
  margin-top: 0.65rem;
  color: var(--text-primary);
  font-size: clamp(1.9rem, 3.4vw, 3rem);
  font-weight: 600;
  letter-spacing: -0.06em;
  line-height: 0.98;
}

.skills-text {
  max-width: 34ch;
  color: var(--text-secondary);
  font-size: 0.84rem;
  line-height: 1.55;
  text-align: right;
}

.skills-frame {
  position: relative;
  overflow: hidden;
  margin-top: 1.7rem;
  padding: 1px;
  border: 1px solid rgba(230, 203, 119, 0.28);
  border-radius: 22px;
  background: rgba(22, 22, 21, 0.8);
  box-shadow: 0 1rem 2.5rem rgba(0, 0, 0, 0.16);
}

.skills-marquee {
  overflow: hidden;
  padding: 0.85rem;
  border-radius: 21px;
  background: rgba(17, 17, 17, 0.92);
}

.skills-track {
  display: flex;
  width: max-content;
  will-change: transform;
  animation: skills-marquee 46s linear infinite;
}

.skills-group {
  display: flex;
  flex-shrink: 0;
  gap: 1.35rem;
  padding-right: 1.35rem;
}

.skills-marquee:hover .skills-track {
  animation-play-state: paused;
}

.skill-pill {
  display: inline-flex;
  align-items: center;
  gap: 0.65rem;
  min-height: 3.05rem;
  padding: 0.5rem 0.95rem 0.5rem 0.55rem;
  border: 1px solid rgba(212, 175, 55, 0.16);
  border-radius: 999px;
  color: #e8e3d5;
  background: linear-gradient(135deg, rgba(38, 38, 36, 0.96), rgba(22, 22, 21, 0.88));
  box-shadow: inset 0 1px rgba(255, 255, 255, 0.08);
  font-size: 0.78rem;
  font-weight: 600;
  white-space: nowrap;
}

.skill-mark {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  width: 2rem;
  height: 2rem;
  border-radius: 10px;
  color: var(--icon-color, #f0d783);
  border: 1px solid rgba(255, 255, 255, 0.13);
  background: rgba(10, 10, 10, 0.72);
  box-shadow: inset 0 1px rgba(255, 255, 255, 0.1), 0 0 0 1px rgba(0, 0, 0, 0.2);
}

.skill-icon {
  width: 1.1rem;
  height: 1.1rem;
  color: var(--icon-color, currentColor);
  fill: currentColor;
  filter: drop-shadow(0 0 3px color-mix(in srgb, currentColor 42%, transparent));
}

.skill-icon-image {
  object-fit: contain;
}

.skill-mark-next {
  border-color: rgba(255, 255, 255, 0.4);
  background: #f2f2f0;
}

@keyframes skills-rise {
  from {
    opacity: 0;
    transform: translateY(1rem);
  }
}

@keyframes skills-marquee {
  to {
    transform: translateX(-33.333333%);
  }
}

@media (max-width: 700px) {
  .skills-heading {
    display: block;
  }

  .skills-text {
    margin-top: 0.7rem;
    text-align: left;
  }
}

@media (prefers-reduced-motion: reduce) {
  .skills-shell,
  .skills-track {
    animation: none;
  }

  .skills-marquee {
    overflow-x: auto;
  }
}
</style>
