// src/components/Footer.jsx
import Image from "next/image";
import logoMark from "../assets/icons/peniel-mark.svg";
import { siGithub } from "simple-icons";

const footerLinkClass = "inline-flex items-center gap-2 rounded-full border border-amber/20 bg-panel px-3 py-2 text-[0.82rem] text-copy no-underline transition hover:text-amber hover:shadow-[0_0_22px_rgba(212,175,55,0.15)]";

export default function Footer() {
  return (
    <footer className="border-t border-white/15 bg-[linear-gradient(110deg,rgba(10,13,18,0.94),rgba(255,255,255,0.08))] px-5 py-8 shadow-[0_1.25rem_3rem_rgba(0,0,0,0.3)] backdrop-blur-2xl sm:py-10">
      <div className="mx-auto flex w-full max-w-[90rem] flex-col items-start gap-5 sm:px-3 md:flex-row md:items-center md:justify-between lg:px-8">
        <a href="#home" className="inline-flex" aria-label="Back to top">
          <Image src={logoMark} alt="Evin logo" className="block size-[34px]" />
        </a>

        <div className="flex flex-wrap gap-3">
          <a href="mailto:yjevin75@gmail.com" className={footerLinkClass}>
            <span className="inline-flex size-6 items-center justify-center rounded-full bg-amber text-[0.68rem] font-bold leading-none text-ink" aria-hidden="true">✉</span>
            <span>Email</span>
          </a>
          <a href="https://github.com/Evin-7" target="_blank" rel="noopener noreferrer" className={footerLinkClass}>
            <span className="inline-flex size-6 items-center justify-center rounded-full bg-amber text-ink" aria-hidden="true">
              <svg viewBox="0 0 24 24" className="size-4 fill-current"><path d={siGithub.path} /></svg>
            </span>
            <span>GitHub</span>
          </a>
          <a href="https://www.linkedin.com/feed/" target="_blank" rel="noopener noreferrer" className={footerLinkClass}>
            <span className="inline-flex size-6 items-center justify-center rounded-full bg-amber text-[0.68rem] font-bold leading-none text-ink" aria-hidden="true">in</span>
            <span>LinkedIn</span>
          </a>
          <a href="tel:+917510255897" className={footerLinkClass}>
            <span className="inline-flex size-6 items-center justify-center rounded-full bg-amber text-[0.68rem] font-bold leading-none text-ink" aria-hidden="true">☎</span>
            <span>+91 7510255897</span>
          </a>
        </div>

        <p className="m-0 text-[0.85rem] text-muted">© {new Date().getFullYear()}</p>
      </div>
    </footer>
  );
}

// src/components/Footer.vue
<template>
  <footer class="footer">
    <div class="footer-shell site-container">
      <div class="footer-brand">
        <img :src="logoMark" alt="Evin logo" class="footer-mark" />
      </div>
      <div class="footer-links">
        <a href="mailto:yjevin75@gmail.com" class="footer-link">
          <span class="footer-link-icon" aria-hidden="true">✉</span>
          <span>Email</span>
        </a>
        <a href="https://github.com/Evin-7" target="_blank" rel="noopener noreferrer" class="footer-link">
          <span class="footer-link-icon" aria-hidden="true">
            <svg viewBox="0 0 24 24" class="footer-brand-icon">
              <path :d="siGithub.path" />
            </svg>
          </span>
          <span>GitHub</span>
        </a>
        <a href="https://www.linkedin.com/feed/" target="_blank" rel="noopener noreferrer" class="footer-link">
          <span class="footer-link-icon" aria-hidden="true">in</span>
          <span>LinkedIn</span>
        </a>
        <a href="tel:+917510255897" class="footer-link">
          <span class="footer-link-icon" aria-hidden="true">☎</span>
          <span>+91 7510255897</span>
        </a>
      </div>
      <p class="footer-meta">&copy; {{ currentYear }}</p>
    </div>
  </footer>
</template>

<script setup>
import logoMark from "../assets/icons/peniel-mark.svg";
import { siGithub } from "simple-icons";

const currentYear = new Date().getFullYear();
</script>

<style scoped>
.footer {
  padding: 3rem 0 4rem;
  background: var(--bg-surface-alt);
  border-top: 1px solid var(--gold-border);
}

.footer-shell {
  display: flex;
  justify-content: space-between;
  gap: 1rem;
  align-items: center;
}

.footer-brand {
  display: inline-flex;
  align-items: center;
}

.footer-mark {
  width: 34px;
  height: 34px;
  display: block;
  filter: sepia(1) saturate(1.2) hue-rotate(2deg) drop-shadow(0 8px 14px var(--gold-glow));
}

.footer-meta {
  font-size: 0.92rem;
  color: var(--text-secondary);
}

.footer-links {
  display: flex;
  gap: 1rem;
  flex-wrap: wrap;
}

.footer-link {
  display: inline-flex;
  align-items: center;
  gap: 0.48rem;
  padding: 0.48rem 0.72rem;
  border-radius: 999px;
  background: var(--bg-surface);
  border: 1px solid var(--gold-border);
  color: var(--text-primary);
  text-decoration: none;
  font-size: 0.92rem;
}

.footer-link-icon {
  width: 1.55rem;
  height: 1.55rem;
  border-radius: 999px;
  background: var(--gold);
  color: var(--bg-primary);
  display: inline-flex;
  align-items: center;
  justify-content: center;
  font-size: 0.68rem;
  font-weight: 700;
  line-height: 1;
}

.footer-brand-icon {
  width: 0.95rem;
  height: 0.95rem;
  fill: currentColor;
}

.footer-link:hover { color: var(--gold); box-shadow: 0 0 22px var(--gold-glow); }

@media (max-width: 640px) {
  .footer-shell {
    flex-direction: column;
    align-items: flex-start;
  }
}
</style>
